```{r}
library(tidyverse)
library(tidytuesdayR)
library(ggwordcloud)
library(tidytext)
```

```{r}
tuesdata <- tidytuesdayR::tt_load(2020, week = 35)

chopped <- tuesdata$chopped

colours <- read_csv("data/colorhexa_com.csv") 

colours <- data.frame(lapply(colours, function(x){
  if (is.character(x)) return(tolower(x))
  else return(x)
}))
colours <- colours %>% 
  mutate_if(is.factor, as.character)

food_words <- read_csv("data/food-related.csv") %>% 
  rename("ingredient" = "-apo-")
rbind(food_words, "cheese")
```
```{r}
appetizer_ingredients <- chopped %>% 
  select(appetizer) %>% 
  unnest_tokens(ingredient, appetizer) %>% 
  inner_join(food_words) %>% 
  anti_join(colours, by = c("ingredient" = "Name")) %>% 
  anti_join(stop_words, by = c("ingredient" = "word")) %>% 
  group_by(ingredient) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count))

```
```{r}
ggwordcloud(
  appetizer_ingredients$ingredient,
  appetizer_ingredients$count,
  min.freq = 15,
  colour = "blue"
)
```
```{r}
entree_ingredients <- chopped %>% 
  select(entree) %>% 
  unnest_tokens(ingredient, entree) %>% 
  inner_join(food_words) %>% 
  anti_join(colours, by = c("ingredient" = "Name")) %>% 
  anti_join(stop_words, by = c("ingredient" = "word")) %>% 
  group_by(ingredient) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count))

```

```{r}
ggwordcloud(
  entree_ingredients$ingredient,
  entree_ingredients$count,
  min.freq = 15,
  colour = "dark green"
)
```
```{r}
dessert_ingredients <- chopped %>% 
  select(dessert) %>% 
  unnest_tokens(ingredient, dessert) %>% 
  inner_join(food_words) %>% 
  anti_join(colours, by = c("ingredient" = "Name")) %>% 
  anti_join(stop_words, by = c("ingredient" = "word")) %>% 
  group_by(ingredient) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count))

```

```{r}
ggwordcloud(
  dessert_ingredients$ingredient,
  dessert_ingredients$count,
  min.freq = 15,
  colors = "purple"
)
```

