```{r}
library(tidyverse)
library(tidytuesdayR)
library(gganimate)
```

```{r}
tuesdata <- tidytuesdayR::tt_load('2020-09-15')
```
```{r}
kids <-tuesdata$kids
```
```{r}
kids_formatted <- kids %>%
  filter(variable == "PK12ed") %>% 
  group_by(year) %>% 
  mutate(rank = rank(-inf_adj_perchild),
         value_rel = inf_adj_perchild/inf_adj_perchild[rank==1],
         value_lbl = paste0(" ",round(inf_adj_perchild))) %>%
  group_by(state) %>%
  filter(rank <=51) %>%
  ungroup()
```

```{r}
kids_plot <- kids_formatted %>% 
  ggplot() +
  geom_bar(aes(x = ))
```
```{r}
staticplot <- ggplot(kids_formatted, aes(rank, group = state,
                fill = as.factor(state), color = as.factor(state))) +
  geom_tile(aes(y = inf_adj_perchild/2,
                height = inf_adj_perchild,
                width = 0.9), alpha = 0.8, color = NA) +
  geom_text(aes(y = 0, label = paste(state, " ")), vjust = 0.2, hjust = 1) +
  geom_text(aes(y=inf_adj_perchild,label = value_lbl, hjust=0)) +
  coord_flip(clip = "off", expand = FALSE) +
  scale_y_continuous(labels = scales::comma) +
  scale_x_reverse() +
  guides(color = FALSE, fill = FALSE) +
  theme(axis.line=element_blank(),
        axis.text.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks=element_blank(),
        axis.title.x=element_blank(),
         axis.title.y=element_blank(),
        legend.position="none",
        panel.background=element_blank(),
        panel.border=element_blank(),
        panel.grid.major=element_blank(),
        panel.grid.minor=element_blank(),
        panel.grid.major.x = element_line( size=.1, color="grey" ),
        panel.grid.minor.x = element_line( size=.1, color="grey" ),
        plot.title=element_text(size=25, hjust=0.5, face="bold", colour="grey", vjust=-1),
        plot.subtitle=element_text(size=18, hjust=0.5, face="italic", color="grey"),
        plot.caption =element_text(size=8, hjust=0.5, face="italic", color="grey"),
        plot.background=element_blank(),
       plot.margin = margin(2,2, 2, 4, "cm"))

```

```{r}
staticplot
```
```{r}
animated_plot <- staticplot +
  transition_states(year, transition_length = 4, state_length = 1) +
  view_follow(fixed_x = TRUE) +
  labs(title = "Spend on Education")
  
```

