```{r}
library(tidyverse)
library(leaflet)
library(ggforce)
```


```{r}
volcano <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-12/volcano.csv')
eruptions <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-12/eruptions.csv')
events <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-12/events.csv')
tree_rings <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-12/tree_rings.csv')
sulfur <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-12/sulfur.csv')
```

```{r}
# creating a dataframe with all of the eruption information with more details about the volcanoes 
volcano_eruptions <- inner_join(volcano, eruptions)
```
```{r}
volcano_icon <- makeIcon("/Users/jennie/git_projects/Tidy-Tuesdays/volcano/images/volcano.png",
 iconWidth = 20, iconHeight = 30,
 iconAnchorX = 22, iconAnchorY = 94)
```

```{r}
#tileOptions(minZoom = 10, maxZoom = 18)
volcano_eruptions %>% 
  leaflet() %>% 
  addTiles() %>%
  addEasyButton(easyButton(
    icon="fa-globe", title="Zoom to Iceland",
    onClick=JS("function(btn, map){ map.setZoom(1); }"))) %>% 
  addMarkers(lng = ~longitude,
                   lat = ~latitude, 
                  popup = ~volcano_name, 
            icon = volcano_icon)
```

Icons made by "https://www.flaticon.com/authors/dinosoftlabs" 



